In [222]:
# Iván Andrés Trujillo Abella
# ivantrujillo1229@gmail.com

In [223]:
#!pip install thefuzz

In [224]:
import pandas as pd
import numpy as np
from thefuzz import fuzz
import re

In [225]:
def clean_text(text):
  text = text.strip().upper().replace(" ","")
  text = text.replace('Á','A')
  text = text.replace('É', 'E')
  text = text.replace('Í', 'I')
  text = text.replace('Ó', 'O')
  text = text.replace('Ú','U')
  return text

def drop_col(df_, threshold):
  df  = df_.copy()
  to_drop = []
  for col in df.columns:
    if (df[col].isnull().sum()/df.shape[0]) >= threshold:
      to_drop.append(col)
  return to_drop


def fix_cols(columns_name):
  new = []
  capture_year = ''
  for token in columns_name:
    if bool(len((re.findall('\d{4}', token)))):
      capture_year = ''.join(re.findall('\d{4}', token))
    new.append(str(capture_year) +  str(token) )
  return new

def capturing(string):
  if bool(re.search(r"(^\d{4}).+(Dólares|Pesos).+(FOB|CIF)", string)):
    result = re.search(r"(^\d{4}).+(Dólares|Pesos).+(FOB|CIF)", string)
    return '-'.join(result.groups())
  else:
    return string


def fuzzy_match(target, sample):
  book = {}
  book[target] = {}
  for element in sample:
    if fuzz.ratio(target, element) > 50 and len("".join(set(element) & set(target)))/len(min(element, target)) > 0.43:
      book[target][element] =  fuzz.ratio(target, element)
  array = sorted(book[target].items(), key=lambda item: int(item[1]), reverse=True)
  if len(array)>= 1:
    return sorted(book[target].items(), key=lambda item: int(item[1]), reverse=True)[0][0]
  else:
    return 'unknown'

In [226]:
url_names = 'https://raw.githubusercontent.com/it-ces/Datasets/main/world.csv'
names = pd.read_csv(url_names)
names.drop(index=names[names['es'].duplicated(keep='first')].index,inplace=True)
names['en'] = names['en'].apply(lambda x : clean_text(str(x)))
names['es'] = names['es'].apply(lambda x : clean_text(str(x)))
book = names[['en', 'es']].set_index('es').to_dict()['en']

In [227]:
url_loc = 'https://raw.githubusercontent.com/it-ces/Datasets/main/Countries-location(google).csv'
url_imp = 'https://raw.githubusercontent.com/it-ces/Datasets/main/dane-importaciones.csv'
url_exp = 'https://raw.githubusercontent.com/it-ces/Datasets/main/dane-exportaciones.csv'
url_pib = 'https://raw.githubusercontent.com/it-ces/Datasets/main/wbdata-gdp-lifeExp-time-series.csv'

In [228]:
info = {}
info['location']  = pd.read_csv(url_loc)
info['import'] = pd.read_csv(url_imp, header=[0,1])
info['export']  = pd.read_csv(url_exp, header=[0,1])
info['gdp'] = pd.read_csv(url_pib)
#info['url_names'] = pd.read_csv(url_names)

In [229]:
info['import'].drop(index=info['import'][info['import']['País']['Unnamed: 1_level_1'].duplicated(keep=False)].index, inplace=True)

In [230]:
info['export'][info['export']['País']['Unnamed: 1_level_1'].duplicated(keep=False)]

Empty DataFrame
Columns: [(Código, Unnamed: 0_level_1), (País, Unnamed: 1_level_1), (1970, Kilos Netos), (Unnamed: 3_level_0, Dólares FOB), (Unnamed: 4_level_0, Pesos FOB), (Unnamed: 5_level_0, Unnamed: 5_level_1), (1971, Kilos Netos), (Unnamed: 7_level_0, Dólares FOB), (Unnamed: 8_level_0, Pesos FOB), (Unnamed: 9_level_0, Unnamed: 9_level_1), (1972, Kilos Netos), (Unnamed: 11_level_0, Dólares FOB), (Unnamed: 12_level_0, Pesos FOB), (Unnamed: 13_level_0, Unnamed: 13_level_1), (1973, Kilos Netos), (Unnamed: 15_level_0, Dólares FOB), (Unnamed: 16_level_0, Pesos FOB), (Unnamed: 17_level_0, Unnamed: 17_level_1), (1974, Kilos Netos), (Unnamed: 19_level_0, Dólares FOB), (Unnamed: 20_level_0, Pesos FOB), (Unnamed: 21_level_0, Unnamed: 21_level_1), (1975, Kilos Netos), (Unnamed: 23_level_0, Dólares FOB), (Unnamed: 24_level_0, Pesos FOB), (Unnamed: 25_level_0, Unnamed: 25_level_1), (1976, Kilos Netos), (Unnamed: 27_level_0, Dólares FOB), (Unnamed: 28_level_0, Pesos FOB), (Unnamed: 29_level_0, Unnamed: 29_level_1), (1977, Kilos Netos), (Unnamed: 31_level_0, Dólares FOB), (Unnamed: 32_level_0, Pesos FOB), (Unnamed: 33_level_0, Unnamed: 33_level_1), (1978, Kilos Netos), (Unnamed: 35_level_0, Dólares FOB), (Unnamed: 36_level_0, Pesos FOB), (Unnamed: 37_level_0, Unnamed: 37_level_1), (1979, Kilos Netos), (Unnamed: 39_level_0, Dólares FOB), (Unnamed: 40_level_0, Pesos FOB), (Unnamed: 41_level_0, Unnamed: 41_level_1), (1980, Kilos Netos), (Unnamed: 43_level_0, Dólares FOB), (Unnamed: 44_level_0, Pesos FOB), (Unnamed: 45_level_0, Unnamed: 45_level_1), (1981, Kilos Netos), (Unnamed: 47_level_0, Dólares FOB), (Unnamed: 48_level_0, Pesos FOB), (Unnamed: 49_level_0, Unnamed: 49_level_1), (1982, Kilos Netos), (Unnamed: 51_level_0, Dólares FOB), (Unnamed: 52_level_0, Pesos FOB), (Unnamed: 53_level_0, Unnamed: 53_level_1), (1983, Kilos Netos), (Unnamed: 55_level_0, Dólares FOB), (Unnamed: 56_level_0, Pesos FOB), (Unnamed: 57_level_0, Unnamed: 57_level_1), (1984, Kilos Netos), (Unnamed: 59_level_0, Dólares FOB), (Unnamed: 60_level_0, Pesos FOB), (Unnamed: 61_level_0, Unnamed: 61_level_1), (1985, Kilos Netos), (Unnamed: 63_level_0, Dólares FOB), (Unnamed: 64_level_0, Pesos FOB), (Unnamed: 65_level_0, Unnamed: 65_level_1), (1986, Kilos Netos), (Unnamed: 67_level_0, Dólares FOB), (Unnamed: 68_level_0, Pesos FOB), (Unnamed: 69_level_0, Unnamed: 69_level_1), (1987, Kilos Netos), (Unnamed: 71_level_0, Dólares FOB), (Unnamed: 72_level_0, Pesos FOB), (Unnamed: 73_level_0, Unnamed: 73_level_1), (1988, Kilos Netos), (Unnamed: 75_level_0, Dólares FOB), (Unnamed: 76_level_0, Pesos FOB), (Unnamed: 77_level_0, Unnamed: 77_level_1), (1989, Kilos Netos), (Unnamed: 79_level_0, Dólares FOB), (Unnamed: 80_level_0, Pesos FOB), (Unnamed: 81_level_0, Unnamed: 81_level_1), (1990, Kilos Netos), (Unnamed: 83_level_0, Dólares FOB), (Unnamed: 84_level_0, Pesos FOB), (Unnamed: 85_level_0, Unnamed: 85_level_1), (1991, Kilos Netos), (Unnamed: 87_level_0, Dólares FOB), (Unnamed: 88_level_0, Pesos FOB), (Unnamed: 89_level_0, Unnamed: 89_level_1), (1992, Kilos Netos), (Unnamed: 91_level_0, Dólares FOB), (Unnamed: 92_level_0, Pesos FOB), (Unnamed: 93_level_0, Unnamed: 93_level_1), (1993, Kilos Netos), (Unnamed: 95_level_0, Dólares FOB), (Unnamed: 96_level_0, Pesos FOB), (Unnamed: 97_level_0, Unnamed: 97_level_1), (1994, Kilos Netos), (Unnamed: 99_level_0, Dólares FOB), ...]
Index: []

[0 rows x 220 columns]

In [231]:
info['export'].drop(columns= drop_col(info['export'], 0.95), inplace=True)
info['export'].columns = [col[0] + re.sub(r'Unnamed:.+', '',col[1]) for col in info['export'].columns]
info['export'].columns = fix_cols(info['export'].columns)
info['export'].columns = [capturing(name) for name in  info['export'].columns]
features_ = list(info['export'].columns[0:2]) + [ col for col in info['export'].columns if bool(len(re.findall(r'FOB',col)))]
info['export'] = info['export'][features_]

In [232]:
info['import'].drop(columns= drop_col(info['import'], 0.99), inplace=True)
info['import'].columns = [col[0] + re.sub(r'Unnamed:.+','',col[1]) for col in info['import'].columns]
info['import'].columns = fix_cols(info['import'].columns)
info['import'].columns = [capturing(name) for name in  info['import'].columns]
# capture FOBS
features_ = list(info['import'].columns[0:2]) + [ col for col in info['import'].columns if bool(len(re.findall(r'FOB',col)))]
info['import'] = info['import'][features_]

In [233]:
info

{'location':     country     latitude    longitude                  name
 0        AD   42.546.245    1.601.554               Andorra
 1        AE   23.424.076   53.847.818  United Arab Emirates
 2        AF    3.393.911   67.709.953           Afghanistan
 3        AG   17.060.816  -61.796.428   Antigua and Barbuda
 4        AI   18.220.554  -63.068.615              Anguilla
 ..      ...          ...          ...                   ...
 240      YE   15.552.727   48.516.388                 Yemen
 241      YT     -128.275   45.166.244               Mayotte
 242      ZA  -30.559.482   22.937.506          South Africa
 243      ZM  -13.133.897   27.849.332                Zambia
 244      ZW  -19.015.438   29.154.857              Zimbabwe

 [245 rows x 4 columns],
 'import':      Código                                               País  \
 1       NaN                                              Total
 3      13.0                                         Afganistán
 4      15.0                                       Aland, Islas
 5      17.0                                            Albania
 6      23.0                                           Alemania
 ..      ...                                                ...
 388   994.0                                            ZFP GEA
 389   996.0  ZFPE Compañía  Operadora Clinica Hispanoamericana
 390   997.0                                  ZFP SurColombiana
 391   998.0      ZFPE Sociedad Portuaria Regional de Cartagena
 392   999.0  Países no precisados en otra parte y desconocidos

      2000-Dólares-FOB     2001-Dólares-FOB     2002-Dólares-FOB  \
 1     10,997,915,190    11,996,605,466.00    11,897,232,853.00
 3              14,733              292,916            1,030,454
 4                   0                    0                    0
 5              35,532               86,503               22,398
 6         463,062,127          516,307,874          485,712,524
 ..                ...                  ...                  ...
 388                 0                    0                   28
 389                 0                    0                    0
 390                 0                    0                    0
 391                 0                    0                    0
 392       209,696,854          362,890,188          313,724,843

         2003-Dólares-FOB  2004-Dólares-FOB  2005-Dólares-FOB  \
 1     13,025,675,812.00    15,648,654,880    19,798,905,453
 3                183,416           457,793            17,149
 4                      0                 0                 0
 5                  3,236           158,833           379,281
 6            591,209,630       640,384,712       733,625,523
 ..                   ...               ...               ...
 388                    0                 0                 0
 389                    0                 0                 0
 390                    0                 0                 0
 391                    0                 0                 0
 392               63,823            46,360       213,908,910

      2006-Dólares-FOB  2007-Dólares-FOB  ...  2015-Dólares-FOB  \
 1     24,534,002,230    30,807,386,992   ...   51,598,039,983
 3             420,710            79,874  ...            19,442
 4                   0                 0  ...                 0
 5             915,128           557,453  ...           489,200
 6         885,624,388     1,146,664,807  ...     2,197,584,511
 ..                ...               ...  ...               ...
 388                 0                 0  ...                 0
 389                 0                 0  ...                 0
 390                 0                 0  ...                 0
 391                 0                 0  ...                 0
 392            17,032            64,038  ...         1,597,066

      2016-Dólares-FOB  2017-Dólares-FOB  2018-Dólares-FOB  2019-Dólares-FOB  \
 1     42,849,436,142    43,972,262,877    48,944,671,500    50,270,764,671
 3             109,287           936,206             8,347            46,583
 4                   0             237.5                 0               932
 5             411,929           232,545           440,951           278,077
 6       1,648,232,017     1,809,091,869     2,106,088,952     2,109,332,812
 ..                ...               ...               ...               ...
 388                 0                 0                 0                 0
 389                 0                 0                 0                 0
 390                 0                 0                 0                 0
 391                 0                 0            39,013                 0
 392                 0                 0                 0                 0

      2020-Dólares-FOB  2021-Dólares-FOB  2022-Dólares-FOB  2023-Dólares-FOB  \
 1     41,185,406,510    56,648,798,983    71,446,374,137    59,445,304,522
 3               1,152             2,228           449,430            27,388
 4                   0                 0                 0                 0
 5             178,729           255,658           320,594           188,928
 6       1,583,402,295     1,974,458,652     2,223,876,557     2,243,929,484
 ..                ...               ...               ...               ...
 388                 0                 0                 0                 0
 389                 0                 0                 0                 0
 390                 0                 0                 0                 0
 391                 0                 0           158,205             2,454
 392                 0            28,359                 0                 0

      2024-Dólares-FOB
 1     24,572,515,154
 3                   0
 4                   0
 5             125,066
 6         864,385,735
 ..                ...
 388                 0
 389                 0
 390                 0
 391                 0
 392                 0

 [391 rows x 27 columns],
 'export':      Código                                               País  \
 0       NaN                                              Total
 1       NaN                                                NaN
 2       2.0                                        ZFP Dorado
 3      13.0                                         Afganistán
 4      15.0                                       Aland, Islas
 ..      ...                                                ...
 386   994.0                                           ZFP GEA
 387   996.0   ZFPE Compañía  Operadora Clinica Hispanoameri...
 388   997.0                                 ZFP SurColombiana
 389   998.0     ZFPE Sociedad Portuaria Regional de Cartagena
 390   999.0   Países no precisados en otra parte y desconoc...

     1970-Dólares-FOB 1970-Pesos-FOB 1971-Dólares-FOB 1971-Pesos-FOB  \
 0        735,657,066           -         690,008,689           -
 1                NaN            NaN              NaN            NaN
 2                  0              0                0              0
 3              4,185              0                0              0
 4                  0              0                0              0
 ..               ...            ...              ...            ...
 386                0              0                0              0
 387                0              0                0              0
 388                0              0                0              0
 389                0              0                0              0
 390           47,123              0                0              0

     1972-Dólares-FOB 1972-Pesos-FOB 1973-Dólares-FOB 1973-Pesos-FOB  ...  \
 0        865,957,616           -       1,177,338,782           -     ...
 1                NaN            NaN              NaN            NaN  ...
 2                  0              0                0              0  ...
 3                  0              0                0              0  ...
 4                  0              0                0              0  ...
 ..               ...            ...              ...            ...  ...
 386                0              0                0              0  ...
 387                0              0                0              0  ...
 388                0              0                0              0  ...
 389                0              0                0              0  ...
 390            7,603              0            1,011              0  ...

      2020-Dólares-FOB         2020-Pesos-FOB  2021-Dólares-FOB  \
 0     31,055,810,660    113,981,030,581,126    41,389,989,071
 1                 NaN                    NaN               NaN
 2                   0                      0                 0
 3              48,561            167,743,249             4,428
 4                   0                      0                 0
 ..                ...                    ...               ...
 386                 0                      0                 0
 387                 0                      0                 0
 388                 0                      0                 0
 389                 0                      0                 0
 390                 0                      0                 0

             2021-Pesos-FOB  2022-Dólares-FOB         2022-Pesos-FOB  \
 0     155,736,811,057,303    56,910,136,648    241,607,564,595,030
 1                      NaN               NaN                    NaN
 2                        0              -                      -
 3               16,550,533              -                      -
 4                        0              -                      -
 ..                     ...               ...                    ...
 386                      0              -                      -
 387                      0              -                      -
 388                      0              -                      -
 389                      0              -                      -
 390                      0              -                      -

      2023-Dólares-FOB         2023-Pesos-FOB  2024-Dólares-FOB  \
 0     49,769,126,318    215,159,245,675,576    20,154,157,442
 1                 NaN                    NaN               NaN
 2                -                      -                 -
 3                -                      -                 -
 4                -                      -                 -
 ..                ...                    ...               ...
 386              -                      -                 -
 387              -                      -                 -
 388          135,910            540,476,495           107,475
 389              -                      -                 -
 390              -                      -                 -

            2024-Pesos-FOB
 0     78,522,240,780,348
 1                     NaN
 2                    -
 3                    -
 4                    -
 ..                    ...
 386                  -
 387                  -
 388          419,344,080
 389                  -
 390                  -

 [391 rows x 112 columns],
 'gdp':               value  year incomeLevel region  lifeExp           Gdp
 0             Aruba  1960         HIC    LCN   64.152           NaN
 1       Afghanistan  1960         LIC    SAS   32.535           NaN
 2            Angola  1960         LMC    SSF   38.211           NaN
 3           Albania  1960         UMC    ECS   54.439           NaN
 4           Andorra  1960         HIC    ECS      NaN           NaN
 ...             ...   ...         ...    ...      ...           ...
 13449        Kosovo  2021         UMC    ECS   76.806  11884.181374
 13450   Yemen, Rep.  2021         LIC    MEA   63.753           NaN
 13451  South Africa  2021         UMC    SSF   62.341  13337.790130
 13452        Zambia  2021         LMC    SSF   61.223   3287.420524
 13453      Zimbabwe  2021         LMC    SSF   59.253   2115.144555

 [13454 rows x 6 columns]}

In [234]:
keys = {}
keys['location']  = 'name'
keys['import'] = 'País'
keys['export'] = 'País'
keys['gdp']  =  'value'

In [235]:
for base in info:
  print(base)
  info[base].rename(columns={keys[base]:'id_key'}, inplace=True)
  info[base]['id_key'] = info[base]['id_key'].apply(lambda x : clean_text(str(x)))
  info[base]['id_key'] = info[base]['id_key'].replace(book)

location
import
export
gdp

In [236]:
all = []
for base in info:
  all = all + list(info[base]['id_key'].unique())
print(len(all))
print(len(set(all)))

gdpset = set(info['gdp']['id_key'].unique())
A = set(info['import']['id_key'].unique())
B = set(info['export']['id_key'].unique())
intersect = (A & B & gdpset)

to_keep = {}
for elemento in A - intersect:
  if fuzzy_match(elemento, gdpset-intersect) != 'unknown':
    if fuzzy_match(elemento, gdpset-intersect) not in to_keep.values():
      to_keep[elemento] =  fuzzy_match(elemento, gdpset-intersect)

1243
486

In [237]:
to_keep

{'CENTROAFRICANA,REPUBLICA': 'CENTRALAFRICANREPUBLIC',
 'EGYPT': 'EGYPT,ARABREP.',
 'HEARDYMCDONALD,ISLAS': 'CAYMANISLANDS',
 'COREA': 'KOREA,REP.',
 'ZFPEAGROSOLERA': 'FAROEISLANDS',
 'TURCASYCAICOS,ISLAS': 'TURKSANDCAICOSISLANDS',
 'TIMORDELESTE': 'TIMOR-LESTE',
 'GAMBIA': 'GAMBIA,THE',
 'TANZANIA,REPUBLICAUNIDADE': 'TANZANIA,UNITEDREPUBLICOF',
 'BAHAMAS': 'BAHAMAS,THE',
 'MICRONESIA,ESTADOSFEDERADOSDE': 'MICRONESIA,FED.STS.',
 'CEILAN': 'CHANNELISLANDS',
 'TOKELAU': 'BELARUS',
 "CÔTED'IVOIRE": "COTED'IVOIRE",
 'CONGO': 'CONGO,REP.',
 'COOK,ISLAS': 'SOLOMONISLANDS',
 'SAINTKITTSANDNEVIS': 'ST.KITTSANDNEVIS',
 'SLOVAKIA': 'SLOVAKREPUBLIC',
 'UNITEDSTATESOFAMERICA': 'UNITEDSTATES',
 'MACEDONIA': 'NORTHMACEDONIA',
 'MARSHALL,ISLAS': 'MARSHALLISLANDS',
 'SAHARAOCCIDENTAL': 'BAHRAIN',
 'KAZAJSTAN': 'KAZAKHSTAN',
 'NUEVAZELANDIA': 'NEWZEALAND',
 'CONGO,REPUBLICADEMOCRATICADEL': 'CONGO,DEM.REP.',
 'TÜRKIYE': 'TURKIYE',
 'IRAN,REPUBLICAISLAMICADE': 'IRAN,ISLAMICREP.',
 'CURAZAO,ISLA': 'CURACAO',
 'ESCOCIA': 'ST.LUCIA',
 'MACAO': 'MACAOSAR,CHINA',
 'HONGKONG': 'HONGKONGSAR,CHINA',
 'ANGLONORMANDAS,ISLAS': 'NORTHERNMARIANAISLANDS',
 'SANMARTIN(PARTEHOLANDESA)': 'ST.MARTIN(FRENCHPART)',
 'SIRIA,REPUBLICAARABE': 'SYRIANARABREPUBLIC',
 'RUSIA,FEDERACIONDE': 'RUSSIANFEDERATION',
 'MARTINIQUE': 'ESWATINI',
 'YEMEN': 'YEMEN,REP.'}

In [238]:
banned = ['ZFPESANVICENTEDEPAUL', 'ESCOCIA',
 'SWAZILANDIA',
'BOUVET,ISLA',
 'SVALBARDYJANMAYEN,ISLAS',
 'VENEZUELA,BOLIVARIANREPUBLICOF',
 'ANTILLASHOLANDESAS',
 'COOK,ISLAS',
 'SAHARAOCCIDENTAL',
 'MAN,ISLA',
 'MARTINIQUE',
 'CEILAN',
 'ANGLONORMANDAS,ISLAS',
  'MOLDAVIA,REPUBLICADE',
 'ALAND,ISLAS',
 'TOKELAU',
 'ZFPEPROTISA',
 'ZFPEAGROSOLERA',
 'ZFPSURCOLOMBIANA',
 'ALEMANIA,REPUBLICADEMOCRATICA',
 'MIDWAY,ISLAS',
  'SANMARTIN(PARTEHOLANDESA)',
 'HEARDYMCDONALD,ISLAS',
 'BONAIRE,ISLA',
 'NORFOLK,ISLAS', ]

new = {}
for unity in to_keep:
  if unity not in  banned:
    new[unity] = to_keep[unity]

In [239]:
new

{'CENTROAFRICANA,REPUBLICA': 'CENTRALAFRICANREPUBLIC',
 'EGYPT': 'EGYPT,ARABREP.',
 'COREA': 'KOREA,REP.',
 'TURCASYCAICOS,ISLAS': 'TURKSANDCAICOSISLANDS',
 'TIMORDELESTE': 'TIMOR-LESTE',
 'GAMBIA': 'GAMBIA,THE',
 'TANZANIA,REPUBLICAUNIDADE': 'TANZANIA,UNITEDREPUBLICOF',
 'BAHAMAS': 'BAHAMAS,THE',
 'MICRONESIA,ESTADOSFEDERADOSDE': 'MICRONESIA,FED.STS.',
 "CÔTED'IVOIRE": "COTED'IVOIRE",
 'CONGO': 'CONGO,REP.',
 'SAINTKITTSANDNEVIS': 'ST.KITTSANDNEVIS',
 'SLOVAKIA': 'SLOVAKREPUBLIC',
 'UNITEDSTATESOFAMERICA': 'UNITEDSTATES',
 'MACEDONIA': 'NORTHMACEDONIA',
 'MARSHALL,ISLAS': 'MARSHALLISLANDS',
 'KAZAJSTAN': 'KAZAKHSTAN',
 'NUEVAZELANDIA': 'NEWZEALAND',
 'CONGO,REPUBLICADEMOCRATICADEL': 'CONGO,DEM.REP.',
 'TÜRKIYE': 'TURKIYE',
 'IRAN,REPUBLICAISLAMICADE': 'IRAN,ISLAMICREP.',
 'CURAZAO,ISLA': 'CURACAO',
 'MACAO': 'MACAOSAR,CHINA',
 'HONGKONG': 'HONGKONGSAR,CHINA',
 'SIRIA,REPUBLICAARABE': 'SYRIANARABREPUBLIC',
 'RUSIA,FEDERACIONDE': 'RUSSIANFEDERATION',
 'YEMEN': 'YEMEN,REP.'}

In [240]:
for base in info:
  info[base]['id_key'] = info[base]['id_key'].replace(new)

In [241]:
len(gdpset & set(info['import']['id_key'].unique()) & set(info['export']['id_key'].unique()))

194

In [242]:
info['gdp_wide'] = info['gdp'].set_index(['id_key', 'year']).unstack(level=-1)

In [243]:
info['gdp_wide'].columns = [col[0] + str(col[1]) for col in info['gdp_wide'].columns]

In [244]:
info['gdp_wide'].reset_index(inplace=True)

In [245]:
# Fixing id_key's
book = {'COREA,REPUBLICADEMOCRATICA':"KOREA,DEM.PEOPLE'SREP.",
        'UNITEDKINGDOMOFGREATBRITAINANDNORTHERNIRELAND':'UNITEDKINGDOM',
        'VENEZUELA,BOLIVARIANREPUBLICOF':'VENEZUELA,RB',
        'VIRGENES(BRITANICAS),ISLAS':'BRITISHVIRGINISLANDS',
        'VIRGENES(DELOSESTADOSUNIDOS),ISLAS':'VIRGINISLANDS(U.S.)',
        'SAINTVINCENTANDTHEGRENADINES':'ST.VINCENTANDTHEGRENADINES',
        'SWAZILANDIA':'ESWATINI',
        'MAN,ISLA':'ISLEOFMAN',
        'LAOS,REPUBLICAPOPULARDEMOCRATICA':'LAOPDR',
        'CAIMAN,ISLAS':'CAYMANISLANDS',
        'CENTROAFRICANA,REPUBLICA':'CENTRALAFRICANREPUBLIC',
        'MARIANASDELNORTE,ISLAS':'NORTHERNMARIANAISLANDS',
        'SLOVAKIA':'SLOVAKREPUBLIC',
        'SANMARTIN(PARTEHOLANDESA)':'SINTMAARTEN(DUTCHPART)'}

info['export'].replace(book, inplace=True)
info['import'].replace(book, inplace=True)

In [246]:
full =info['gdp_wide'].merge(info['export'],
                       on='id_key',)

In [247]:
full.columns

Index(['id_key', 'incomeLevel1960', 'incomeLevel1961', 'incomeLevel1962',
       'incomeLevel1963', 'incomeLevel1964', 'incomeLevel1965',
       'incomeLevel1966', 'incomeLevel1967', 'incomeLevel1968',
       ...
       '2020-Dólares-FOB', '2020-Pesos-FOB', '2021-Dólares-FOB',
       '2021-Pesos-FOB', '2022-Dólares-FOB', '2022-Pesos-FOB',
       '2023-Dólares-FOB', '2023-Pesos-FOB', '2024-Dólares-FOB',
       '2024-Pesos-FOB'],
      dtype='object', length=360)

In [248]:
full = full.merge(info['import'], on='id_key', suffixes=('export','import'))

In [249]:
full.columns

Index(['id_key', 'incomeLevel1960', 'incomeLevel1961', 'incomeLevel1962',
       'incomeLevel1963', 'incomeLevel1964', 'incomeLevel1965',
       'incomeLevel1966', 'incomeLevel1967', 'incomeLevel1968',
       ...
       '2015-Dólares-FOBimport', '2016-Dólares-FOBimport',
       '2017-Dólares-FOBimport', '2018-Dólares-FOBimport',
       '2019-Dólares-FOBimport', '2020-Dólares-FOBimport',
       '2021-Dólares-FOBimport', '2022-Dólares-FOBimport',
       '2023-Dólares-FOBimport', '2024-Dólares-FOBimport'],
      dtype='object', length=386)

In [250]:
def format_coordinate(coor):
  coor = re.sub(r"\.", "_" ,coor, count=1)
  coor = re.sub(r"\.", "", coor)
  coor = re.sub(r'_', '.', coor)
  return float(coor)

In [251]:
info['location']['latitude'] = info['location']['latitude'].apply(lambda x: format_coordinate(str(x)))
info['location']['longitude'] = info['location']['longitude'].apply(lambda x: format_coordinate(str(x)))

In [252]:
def distance(longitudei, latitudei, longitudej, latitudej):
  return ((longitudei - longitudej)**2 + (latitudei - latitudej)**2)**0.5

In [253]:
col_latitude = 4.570868
col_longitude =  -74.297333

In [254]:
distance(col_longitude, col_latitude, col_longitude, col_latitude)

0.0

In [255]:
info['location']['distance'] = info['location'].apply(lambda col:  distance(col_longitude, col_latitude,  col['longitude'], col['latitude']), axis=1)

In [256]:
book = {'COREA,REPUBLICADEMOCRATICA':"KOREA,DEM.PEOPLE'SREP.",
        'UNITEDKINGDOMOFGREATBRITAINANDNORTHERNIRELAND':'UNITEDKINGDOM',
        'VENEZUELA,BOLIVARIANREPUBLICOF':'VENEZUELA,RB',
        'VIRGENES(BRITANICAS),ISLAS':'BRITISHVIRGINISLANDS',
        'VIRGENES(DELOSESTADOSUNIDOS),ISLAS':'VIRGINISLANDS(U.S.)',
        'SAINTVINCENTANDTHEGRENADINES':'ST.VINCENTANDTHEGRENADINES',
        'SWAZILANDIA':'ESWATINI',
        'MAN,ISLA':'ISLEOFMAN',
        'LAOS,REPUBLICAPOPULARDEMOCRATICA':'LAOPDR',
        'CAIMAN,ISLAS':'CAYMANISLANDS',
        'CENTROAFRICANA,REPUBLICA':'CENTRALAFRICANREPUBLIC',
        'MARIANASDELNORTE,ISLAS':'NORTHERNMARIANAISLANDS',
        'SLOVAKIA':'SLOVAKREPUBLIC',
        'SANMARTIN(PARTEHOLANDESA)':'SINTMAARTEN(DUTCHPART)'}

In [257]:
info['location'].replace(book, inplace=True)

In [258]:
full =full.merge(info['location'], on='id_key', how = 'outer', indicator=True)

In [259]:
full[full['_merge']=='left_only']['id_key'].unique()

array(['CABOVERDE', 'CONGO,DEM.REP.', 'CONGO,REP.', 'CURACAO', 'CZECHIA',
       'ESWATINI', 'IRAN,ISLAMICREP.', "KOREA,DEM.PEOPLE'SREP.",
       'KOREA,REP.', 'LAOPDR', 'MACAOSAR,CHINA', 'MICRONESIA,FED.STS.',
       'MYANMAR', 'NORTHMACEDONIA', 'RUSSIANFEDERATION',
       'SAOTOMEANDPRINCIPE', 'SINTMAARTEN(DUTCHPART)', 'SOUTHSUDAN',
       'SYRIANARABREPUBLIC', 'TURKIYE', 'VIRGINISLANDS(U.S.)'],
      dtype=object)

In [260]:
full[full['_merge']=='right_only']['id_key'].unique()

array(['ANGUILLA', 'ANTARCTICA', 'BAHRAIN', 'BELARUS', 'BOUVETISLAND',
       'BRITISHINDIANOCEANTERRITORY', 'CAPEVERDE', 'CHRISTMASISLAND',
       'COCOS[KEELING]ISLANDS', 'CONGO[DRC]', 'CONGO[REPUBLIC]',
       'COOKISLANDS', 'CZECHREPUBLIC', 'FALKLANDISLANDS[ISLASMALVINAS]',
       'FAROEISLANDS', 'FRENCHGUIANA', 'FRENCHSOUTHERNTERRITORIES',
       'GAZASTRIP', 'GUADELOUPE', 'GUERNSEY',
       'HEARDISLANDANDMCDONALDISLANDS', 'IRAN,ISLAMICREPUBLICOF',
       'JERSEY', 'KOSOVO', 'KYRGYZSTAN', "LAOPEOPLE'SDEMOCRATICREPUBLIC",
       'MACAU', 'MACEDONIA[FYROM]', 'MARTINIQUE', 'MAYOTTE',
       'MICRONESIA,FEDERATEDSTATESOF', 'MOLDOVA', 'MONTSERRAT',
       'MYANMAR[BURMA]', 'NETHERLANDSANTILLES', 'NIUE', 'NORFOLKISLAND',
       'NORTHKOREA', 'PALESTINIANTERRITORIES', 'PITCAIRNISLANDS',
       'REUNION', 'RUSSIA', 'SAINTHELENA', 'SAINTLUCIA',
       'SAINTPIERREANDMIQUELON', 'SOLOMONISLANDS',
       'SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS', 'SOUTHKOREA',
       'SVALBARDANDJANMAYEN', 'SWAZILAND', 'SYRIA', 'SÃOTOMEANDPRINCIPE',
       'TAIWAN', 'TOKELAU', 'TURKEY', 'U.S.MINOROUTLYINGISLANDS',
       'U.S.VIRGINISLANDS', 'VATICANCITY', 'WALLISANDFUTUNA',
       'WESTERNSAHARA'], dtype=object)

In [261]:
full['_merge'].value_counts()

_merge
both          185
right_only     60
left_only      21
Name: count, dtype: int64

In [262]:
full.columns

Index(['id_key', 'incomeLevel1960', 'incomeLevel1961', 'incomeLevel1962',
       'incomeLevel1963', 'incomeLevel1964', 'incomeLevel1965',
       'incomeLevel1966', 'incomeLevel1967', 'incomeLevel1968',
       ...
       '2020-Dólares-FOBimport', '2021-Dólares-FOBimport',
       '2022-Dólares-FOBimport', '2023-Dólares-FOBimport',
       '2024-Dólares-FOBimport', 'country', 'latitude', 'longitude',
       'distance', '_merge'],
      dtype='object', length=391)

In [264]:
test = full[['id_key', '2020-Dólares-FOBexport', '2020-Dólares-FOBimport', 'Gdp2020', 'distance']]

In [276]:
test

,id_key,2020-Dólares-FOBexport,2020-Dólares-FOBimport,Gdp2020,distance,exterior
0,AFGHANISTAN,"48,561","1,152",1968.341002,142.012163,"48,5611,152"
1,ALBANIA,"873,316","178,729",13278.434516,101.301719,"873,316178,729"
2,ALGERIA,"3,677,841","20,799,046",10844.770764,79.498257,"3,677,84120,799,046"
3,AMERICANSAMOA,0,"3,634",NaN,97.669545,"03,634"
4,ANDORRA,0,"167,186",NaN,84.869136,"0167,186"
...,...,...,...,...,...,...
261,WALLISANDFUTUNA,NaN,NaN,NaN,104.480941,NaN
262,WESTERNSAHARA,NaN,NaN,NaN,64.477010,NaN
263,"YEMEN,REP.","1,282,789",0,NaN,123.303736,"1,282,7890"
264,ZAMBIA,"120,842",0,3183.650773,103.669667,"120,8420"
265,ZIMBABWE,"5,405","1,191",1990.319419,106.106877,"5,4051,191"

In [268]:
test['exterior'] = test['2020-Dólares-FOBexport'] + test['2020-Dólares-FOBimport']

/tmp/ipython-input-268-3404487237.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['exterior'] = test['2020-Dólares-FOBexport'] + test['2020-Dólares-FOBimport']

In [275]:
test[['Gdp2020', 'distance', 'exterior']].dtypes

Gdp2020     float64
distance    float64
exterior     object
dtype: object